/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.BudgetController;
import flpm.GlobalSession;
import java.awt.BorderLayout;
import javax.swing.JLabel;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import models.BudgetModel;
import org.jdesktop.swingx.autocomplete.AutoCompleteDecorator;

/**
 *
 * @author niki
 */
public class BudgetPanel extends javax.swing.JPanel {
    private JTable budgetTable; // the table displayed on the GUI
    private BudgetController budgetController; // glue between model and gui
    /**
     * Creates new form BudgetPanel
     */
    public BudgetPanel() {
        initComponents();
        errorCode.setVisible(false);
        budgetController = new BudgetController(this);
        addJTable();
        String role=GlobalSession.user_role;
         if(role.equals("Student")){
            addButton.setVisible(false);
            deleteButton.setVisible(false);
            updateButton.setVisible(false);
        }
    }
    public void addJTable() {   
    	budgetTable = new JTable(budgetController.getTableModel());
        budgetTable.getSelectionModel().addListSelectionListener(budgetController);
        JScrollPane scrollpane = new JScrollPane(budgetTable);
        tablePanel.setLayout(new BorderLayout());
    	tablePanel.add(scrollpane, BorderLayout.CENTER);		
    }
    public void updateTable() {
    	budgetTable.setModel(budgetController.getTableModel());
    }
    // display data on the courseNameTextField
    public void setitem_idTextField(String value) {
    	item_idTextField.setText(value);
    } 
    // display data on the courseNumberTextField
    public void setproject_idTextField(String value) {
    	projectCombo.setSelectedItem(value);
    }
    
    // display data on the enrollmentTextField
    public void setitem_nameTextField(String value) {
    	item_nameTextField.setText(value);
    }
    
    // display data on the startDateTextField
    public void setestimated_costTextField(String value) {
    estimated_costTextField.setText(value);
    }
    
    // display data on the endDateTextField
    public void setactual_costTextField(String value) {
    	actual_costTextField.setText(value);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        PersistenceUnitEntityManager = java.beans.Beans.isDesignTime() ? null : javax.persistence.Persistence.createEntityManagerFactory("PersistenceUnit").createEntityManager();
        if(!GlobalSession.user_role.equals("Admin")){
            projectQuery = java.beans.Beans.isDesignTime() ? null : PersistenceUnitEntityManager.createQuery("SELECT p.projectName FROM Project p,MemberProject mp where p.projectName=mp.memberProjectPK.projectName and mp.memberProjectPK.userId=:user");
            projectQuery.setParameter("user", GlobalSession.user_id);
        }
        else{
            projectQuery = java.beans.Beans.isDesignTime() ? null : PersistenceUnitEntityManager.createQuery("SELECT p.projectName FROM Project p");
        }
        projectList = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : projectQuery.getResultList();
        itemID_label = new javax.swing.JLabel();
        itemName_label = new javax.swing.JLabel();
        project_label = new javax.swing.JLabel();
        estimatedCost_label = new javax.swing.JLabel();
        actualCost_Label = new javax.swing.JLabel();
        item_idTextField = new javax.swing.JTextField();
        item_nameTextField = new javax.swing.JTextField();
        estimated_costTextField = new javax.swing.JTextField();
        actual_costTextField = new javax.swing.JTextField();
        addButton = new javax.swing.JButton();
        updateButton = new javax.swing.JButton();
        deleteButton = new javax.swing.JButton();
        tablePanel = new javax.swing.JPanel();
        projectCombo = new org.jdesktop.swingx.JXComboBox();
        applyFilterButton = new javax.swing.JButton();
        errorCode = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        itemID_label.setText("Item ID");

        itemName_label.setText("Item Name ");

        project_label.setText("Project ");

        estimatedCost_label.setText("Estimated Cost");

        actualCost_Label.setText("Actual Cost");

        item_idTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                item_idTextFieldActionPerformed(evt);
            }
        });

        item_nameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                item_nameTextFieldActionPerformed(evt);
            }
        });

        estimated_costTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                estimated_costTextFieldActionPerformed(evt);
            }
        });

        actual_costTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actual_costTextFieldActionPerformed(evt);
            }
        });

        addButton.setText("Add");
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });

        updateButton.setText("Update");
        updateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateButtonActionPerformed(evt);
            }
        });

        deleteButton.setText("Delete");
        deleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout tablePanelLayout = new javax.swing.GroupLayout(tablePanel);
        tablePanel.setLayout(tablePanelLayout);
        tablePanelLayout.setHorizontalGroup(
            tablePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 416, Short.MAX_VALUE)
        );
        tablePanelLayout.setVerticalGroup(
            tablePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 139, Short.MAX_VALUE)
        );

        org.jdesktop.beansbinding.ELProperty eLProperty = org.jdesktop.beansbinding.ELProperty.create("${resultList}");
        org.jdesktop.swingbinding.JComboBoxBinding jComboBoxBinding = org.jdesktop.swingbinding.SwingBindings.createJComboBoxBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, projectQuery, eLProperty, projectCombo);
        bindingGroup.addBinding(jComboBoxBinding);

        projectCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                projectComboActionPerformed(evt);
            }
        });
        AutoCompleteDecorator.decorate(projectCombo);

        applyFilterButton.setText("Apply Filter");
        applyFilterButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                applyFilterButtonActionPerformed(evt);
            }
        });

        errorCode.setForeground(new java.awt.Color(0, 51, 255));
        errorCode.setText(" No item budgets to show");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(itemName_label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(itemID_label)
                                    .addComponent(project_label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(estimatedCost_label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(actualCost_Label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addComponent(addButton, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(40, 40, 40)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(errorCode, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(projectCombo, javax.swing.GroupLayout.DEFAULT_SIZE, 230, Short.MAX_VALUE)
                                            .addComponent(deleteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(actual_costTextField)
                                            .addComponent(estimated_costTextField, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(item_nameTextField, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(item_idTextField, javax.swing.GroupLayout.Alignment.LEADING))
                                        .addGap(18, 18, 18)
                                        .addComponent(applyFilterButton))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(31, 31, 31)
                                .addComponent(updateButton, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(tablePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 174, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(errorCode)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(projectCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(project_label, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(applyFilterButton))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(item_idTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(itemID_label))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(item_nameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(itemName_label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(estimatedCost_label)
                    .addComponent(estimated_costTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(actualCost_Label)
                    .addComponent(actual_costTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(deleteButton)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(updateButton)
                        .addComponent(addButton)))
                .addGap(28, 28, 28)
                .addComponent(tablePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        bindingGroup.bind();
    }// </editor-fold>//GEN-END:initComponents

    private void item_idTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_item_idTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_item_idTextFieldActionPerformed

    private void item_nameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_item_nameTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_item_nameTextFieldActionPerformed

    private void estimated_costTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_estimated_costTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_estimated_costTextFieldActionPerformed

    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
        String[] array = new String[budgetTable.getColumnCount()];
    	array[0] = item_idTextField.getText();
    	array[1] = projectCombo.getSelectedItem().toString();
    	array[2] = item_nameTextField.getText();
    	array[3] = estimated_costTextField.getText();
    	array[4] = actual_costTextField.getText();
        budgetController.addRow( array);
    }//GEN-LAST:event_addButtonActionPerformed

    private void deleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButtonActionPerformed
        String[] array = new String[budgetTable.getColumnCount()];
    	array[0] = item_idTextField.getText();
    	array[1] = projectCombo.getSelectedItem().toString();
    	array[2] = item_nameTextField.getText();
        array[3] = estimated_costTextField.getText();
    	array[4] = actual_costTextField.getText();
    	budgetController.deleteRow(array);
        ( (BudgetModel) budgetTable.getModel()).fireTableDataChanged();
    }//GEN-LAST:event_deleteButtonActionPerformed

    private void projectComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_projectComboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_projectComboActionPerformed

    private void applyFilterButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_applyFilterButtonActionPerformed
        String projectName=projectCombo.getSelectedItem().toString();
        budgetController.applyFilter(projectName);
        ( (BudgetModel) budgetTable.getModel()).fireTableDataChanged();
    }//GEN-LAST:event_applyFilterButtonActionPerformed

    private void actual_costTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_actual_costTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_actual_costTextFieldActionPerformed

    private void updateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateButtonActionPerformed
        String[] array = new String[budgetTable.getColumnCount()];
    	array[0] = item_idTextField.getText();
    	array[1] = projectCombo.getSelectedItem().toString();
    	array[2] = item_nameTextField.getText();
        array[3] = estimated_costTextField.getText();
    	array[4] = actual_costTextField.getText();
    	budgetController.updateRow(array);
        ( (BudgetModel) budgetTable.getModel()).fireTableDataChanged();
    }//GEN-LAST:event_updateButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.persistence.EntityManager PersistenceUnitEntityManager;
    private javax.swing.JLabel actualCost_Label;
    private javax.swing.JTextField actual_costTextField;
    private javax.swing.JButton addButton;
    private javax.swing.JButton applyFilterButton;
    private javax.swing.JButton deleteButton;
    private javax.swing.JLabel errorCode;
    private javax.swing.JLabel estimatedCost_label;
    private javax.swing.JTextField estimated_costTextField;
    private javax.swing.JLabel itemID_label;
    private javax.swing.JLabel itemName_label;
    private javax.swing.JTextField item_idTextField;
    private javax.swing.JTextField item_nameTextField;
    private org.jdesktop.swingx.JXComboBox projectCombo;
    private java.util.List<entity.Project> projectList;
    private javax.persistence.Query projectQuery;
    private javax.swing.JLabel project_label;
    private javax.swing.JPanel tablePanel;
    private javax.swing.JButton updateButton;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables

    public JLabel getErrorCode() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
