/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.CardLayout;

/**
 *
 * @author niki
 */
public class ClientPanel extends javax.swing.JPanel {

    /**
     * Creates new form ClientPanel
     */
    public ClientPanel() {
        initComponents();
        viewPanel.setLayout(new CardLayout());
        viewPanel.add(new CommunicationPanel(),"communication");
        viewPanel.add(new ProjectPanel(),"project panel");
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        viewPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        adminTree = new javax.swing.JTree();

        setBackground(new java.awt.Color(255, 255, 255));

        viewPanel.setLayout(new CardLayout());
        viewPanel.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout viewPanelLayout = new javax.swing.GroupLayout(viewPanel);
        viewPanel.setLayout(viewPanelLayout);
        viewPanelLayout.setHorizontalGroup(
            viewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 416, Short.MAX_VALUE)
        );
        viewPanelLayout.setVerticalGroup(
            viewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 330, Short.MAX_VALUE)
        );

        javax.swing.tree.DefaultMutableTreeNode treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("Frugal Lab Tool");
        javax.swing.tree.DefaultMutableTreeNode treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("Project");
        javax.swing.tree.DefaultMutableTreeNode treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("Project Details");
        treeNode2.add(treeNode3);
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("Communication");
        treeNode2.add(treeNode3);
        treeNode1.add(treeNode2);
        adminTree.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
        adminTree.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                adminTreeMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(adminTree);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(viewPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(viewPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 330, Short.MAX_VALUE))
                .addGap(6, 6, 6))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void adminTreeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_adminTreeMouseClicked
        CardLayout cardLayout = (CardLayout)(viewPanel.getLayout());
        String node=adminTree.getLastSelectedPathComponent().toString();
        switch(node){
            case "Project Details" : cardLayout.show(viewPanel, "project panel");
            break;
            case "Team Members"    : cardLayout.show(viewPanel,"member project panel");
            break;
            case "Tasks"           : cardLayout.show(viewPanel,"task panel");
            break;
            case "Budget"          : cardLayout.show(viewPanel,"budget panel");
            break;
            case "Users"           : cardLayout.show(viewPanel,"user panel");
            break;
            case "Member Name"     : cardLayout.show(viewPanel, "search_by_member");
            break;
            case "Project Name"    : cardLayout.show(viewPanel, "search_by_project");
            break;
            case "Timeline"        : cardLayout.show(viewPanel, "timeline");
            break;
            case "Task Dependencies" : cardLayout.show(viewPanel,"task dependency");
            break;
            case "Communication" : cardLayout.show(viewPanel,"communication");
            break;

        }
    }//GEN-LAST:event_adminTreeMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTree adminTree;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel viewPanel;
    // End of variables declaration//GEN-END:variables
}
