/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.MemberProjectController;
import flpm.GlobalSession;
import java.awt.BorderLayout;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import models.MemberProjectModel;
import org.jdesktop.swingx.autocomplete.AutoCompleteDecorator;

/**
 *
 * @author niki
 */
public class MemberProjectPanel extends javax.swing.JPanel {

    /**
     * Creates new form MemberProjectPanel
     */
    private JTable memberProjectTable; // the table displayed on the GUI
    private MemberProjectController memberProjectController; // glue between model and gui
    public MemberProjectPanel() {
        initComponents();
        memberProjectController = new MemberProjectController(this);
        addJTable();
        String role=GlobalSession.user_role;
        if(role.equals("Student") || role.equals("Client")){
           addButton.setVisible(false);
           removeButton.setVisible(false);
        }
    }
    public void addJTable() {
    	memberProjectTable = new JTable(memberProjectController.getTableModel());
        memberProjectTable.getSelectionModel().addListSelectionListener(memberProjectController);
        JScrollPane scrollpane = new JScrollPane(memberProjectTable);
    	tablePanel.setLayout(new BorderLayout());
    	tablePanel.add(scrollpane, BorderLayout.CENTER);
    }
    public void updateTable() {
    	memberProjectTable.setModel(memberProjectController.getTableModel());
    }
    public void setProjectName(String project_name){
        projectCombo.setSelectedItem(project_name);
    }
    public void setMemberName(String user_id){
        userCombo.setSelectedItem(user_id);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        PersistenceUnitEntityManager0 = java.beans.Beans.isDesignTime() ? null : javax.persistence.Persistence.createEntityManagerFactory("PersistenceUnit").createEntityManager();
        if(!GlobalSession.user_role.equals("Admin")){
            projectQuery = java.beans.Beans.isDesignTime() ? null : PersistenceUnitEntityManager0.createQuery("SELECT p.projectName FROM Project p,MemberProject mp where p.projectName=mp.memberProjectPK.projectName and mp.memberProjectPK.userId=:user");
            projectQuery.setParameter("user", GlobalSession.user_id);
        }
        else{
            projectQuery = java.beans.Beans.isDesignTime() ? null : PersistenceUnitEntityManager0.createQuery("SELECT p.projectName FROM Project p");
        }
        projectList = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : projectQuery.getResultList();
        usersQuery = java.beans.Beans.isDesignTime() ? null : PersistenceUnitEntityManager0.createQuery("SELECT u.userId FROM Users u");
        usersList = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : usersQuery.getResultList();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        projectCombo = new org.jdesktop.swingx.JXComboBox();
        jLabel4 = new javax.swing.JLabel();
        userCombo = new org.jdesktop.swingx.JXComboBox();
        tablePanel = new javax.swing.JPanel();
        addButton = new javax.swing.JButton();
        removeButton = new javax.swing.JButton();

        jButton1.setText("jButton1");

        setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setText("Project");

        org.jdesktop.beansbinding.ELProperty eLProperty = org.jdesktop.beansbinding.ELProperty.create("${resultList}");
        org.jdesktop.swingbinding.JComboBoxBinding jComboBoxBinding = org.jdesktop.swingbinding.SwingBindings.createJComboBoxBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, projectQuery, eLProperty, projectCombo);
        bindingGroup.addBinding(jComboBoxBinding);

        AutoCompleteDecorator.decorate(projectCombo);

        jLabel4.setText("Member");

        eLProperty = org.jdesktop.beansbinding.ELProperty.create("${resultList}");
        jComboBoxBinding = org.jdesktop.swingbinding.SwingBindings.createJComboBoxBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, usersQuery, eLProperty, userCombo);
        bindingGroup.addBinding(jComboBoxBinding);

        AutoCompleteDecorator.decorate(userCombo);

        javax.swing.GroupLayout tablePanelLayout = new javax.swing.GroupLayout(tablePanel);
        tablePanel.setLayout(tablePanelLayout);
        tablePanelLayout.setHorizontalGroup(
            tablePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        tablePanelLayout.setVerticalGroup(
            tablePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 122, Short.MAX_VALUE)
        );

        addButton.setText("Add");
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });

        removeButton.setText("Remove");
        removeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(addButton, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 100, Short.MAX_VALUE)
                        .addComponent(removeButton))
                    .addComponent(tablePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(projectCombo, javax.swing.GroupLayout.DEFAULT_SIZE, 193, Short.MAX_VALUE)
                            .addComponent(userCombo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(111, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(projectCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(userCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(tablePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addButton)
                    .addComponent(removeButton))
                .addContainerGap(38, Short.MAX_VALUE))
        );

        bindingGroup.bind();
    }// </editor-fold>//GEN-END:initComponents

    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
        String[] array = new String[memberProjectTable.getColumnCount()];
    	array[0] = projectCombo.getSelectedItem().toString();
    	array[1] = userCombo.getSelectedItem().toString();
        memberProjectController.addRow( array);
        
    }//GEN-LAST:event_addButtonActionPerformed

    private void removeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeButtonActionPerformed
        String[] array = new String[memberProjectTable.getColumnCount()];
    	array[0] = projectCombo.getSelectedItem().toString();
    	array[1] = userCombo.getSelectedItem().toString();
        memberProjectController.deleteRow( array[0],array[1]);
        ( (MemberProjectModel)memberProjectTable.getModel()).fireTableDataChanged();

    }//GEN-LAST:event_removeButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.persistence.EntityManager PersistenceUnitEntityManager0;
    private javax.swing.JButton addButton;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private org.jdesktop.swingx.JXComboBox projectCombo;
    private java.util.List<entity.Project> projectList;
    private javax.persistence.Query projectQuery;
    private javax.swing.JButton removeButton;
    private javax.swing.JPanel tablePanel;
    private org.jdesktop.swingx.JXComboBox userCombo;
    private java.util.List<entity.Users> usersList;
    private javax.persistence.Query usersQuery;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables
}
