/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.ProjectController;
import flpm.GlobalSession;
import java.awt.BorderLayout;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import models.ProjectModel;
import org.jdesktop.swingx.autocomplete.AutoCompleteDecorator;

/**
 *
 * @author niki
 */
public class ProjectPanel extends javax.swing.JPanel {

    /**
     * Creates new form ProjectPanel
     */
    
   private JTable jtable1; // the table displayed on the GUI
   private ProjectController projectController; // glue between model and gui

    public ProjectPanel() {
        initComponents();
        addButton.setVisible(false);
        updateButton.setVisible(false);
        deleteButton.setVisible(false);
        String role=GlobalSession.user_role;
        if(role.equals("Admin") ){
           addButton.setVisible(true);
           updateButton.setVisible(true);
           deleteButton.setVisible(true);
        }
        projectController = new ProjectController(this);
        addJTable();
    }
    public void addJTable() {  
    	jtable1 = new JTable(projectController.getTableModel());
    	jtable1.getSelectionModel().addListSelectionListener(projectController);
        JScrollPane scrollpane = new JScrollPane(jtable1);
        jPanel3.setLayout(new BorderLayout());
    	jPanel3.add(scrollpane, BorderLayout.CENTER);
    }
    public void updateTable() {
    	jtable1.setModel(projectController.getTableModel());
    }
    public String getProjectNameTextField() {
	return projectNameTextField.getText();
    }
    public void setProjectNameTextField(String
	projectName) {
            this.projectNameTextField.setText(projectName);
    }
    public void setProjectStatus(String status) {
        statusCombo.setSelectedItem(status);
    }
    public String getProjectDescriptionTextArea() {
	return projectDescriptionTextArea.getText();
	}
    public void setProjectDescriptionTextArea(String projectDescription)
	{
	this.projectDescriptionTextArea.setText(projectDescription);
	}
    public String getProjectOutcomeTextField() {
	return projectOutcomeTextField.getText();
	}
    public void setProjectOutcomeTextField(String projectOutcome) {
	this.projectOutcomeTextField.setText(projectOutcome);
	}
    public String getProjectTagTextField() {
	return projectTagTextField.getText();
	}
    public void setProjectTagTextField(String projectTag) {
	this.projectTagTextField.setText(projectTag);
	}
    
	
    public String getProjectInchargeIDTextField() {
	return inchargeCombo.getSelectedItem().toString();
	}
    public void setProjectInchargeIDTextField(String projectIncharge) {
	       inchargeCombo.setSelectedItem(projectIncharge);
	}
    public String getProjectClientIDTextField() {
	return clientCombo.getSelectedItem().toString();
     }
    public void setProjectClientIDTextField(String projectClientIDText) {
	 clientCombo.setSelectedItem(projectClientIDText);
    }
    
    public void setProjectStartDateChooser (String d) {
        DateFormat format = new SimpleDateFormat();
        Date date=null;
        if(d==null){
            return;
        }
         try {
             date = format.parse(d);
         } catch (ParseException ex) {
             Logger.getLogger(ProjectPanel.class.getName()).log(Level.SEVERE, null, ex);
         }
        projectStartDate.setDate(date);
    }
    
    public void setProjectEndDateChooser (String d) {
        DateFormat format = new SimpleDateFormat();
        Date date=null;
        if(d==null){
            return;
        }
         try {
             date = format.parse(d);
         } catch (ParseException ex) {
             Logger.getLogger(ProjectPanel.class.getName()).log(Level.SEVERE, null, ex);
         }
        projectEndDate.setDate(date);
    }
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        PersistenceUnitEntityManager = java.beans.Beans.isDesignTime() ? null : javax.persistence.Persistence.createEntityManagerFactory("PersistenceUnit").createEntityManager();
        usersQuery = java.beans.Beans.isDesignTime() ? null : PersistenceUnitEntityManager.createQuery("SELECT u.userId FROM Users u where u.userRole=:frole or u.userRole=:mrole");
        usersQuery.setParameter("frole","Faculty Advisor");
        usersQuery.setParameter("mrole","Manager");
        usersList = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : usersQuery.getResultList();
        usersQuery1 = java.beans.Beans.isDesignTime() ? null : PersistenceUnitEntityManager.createQuery("SELECT u.userName FROM Users u where u.userRole=:role");
        usersQuery1.setParameter("role", "Client");
        usersList1 = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : usersQuery1.getResultList();
        projectPane = new javax.swing.JPanel();
        projectName = new javax.swing.JLabel();
        projectNameTextField = new javax.swing.JTextField();
        inchargeID = new javax.swing.JLabel();
        clientID = new javax.swing.JLabel();
        projectStatus = new javax.swing.JLabel();
        projectDescription = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        projectDescriptionTextArea = new javax.swing.JTextArea();
        projectOutcome = new javax.swing.JLabel();
        projectTag = new javax.swing.JLabel();
        projectTagTextField = new javax.swing.JTextField();
        startDate = new javax.swing.JLabel();
        addButton = new javax.swing.JButton();
        deleteButton = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        statusCombo = new javax.swing.JComboBox();
        endDate = new javax.swing.JLabel();
        projectOutcomeTextField = new javax.swing.JTextField();
        projectStartDate = new com.toedter.calendar.JDateChooser();
        projectEndDate = new com.toedter.calendar.JDateChooser();
        updateButton = new javax.swing.JButton();
        inchargeCombo = new org.jdesktop.swingx.JXComboBox();
        clientCombo = new org.jdesktop.swingx.JXComboBox();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        projectPane.setBackground(new java.awt.Color(255, 255, 255));

        projectName.setText("Name");

        projectNameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                projectNameTextFieldActionPerformed(evt);
            }
        });

        inchargeID.setText("Incharge ID");

        clientID.setText("Client ID");

        projectStatus.setText("Status");

        projectDescription.setText("Description");

        projectDescriptionTextArea.setColumns(20);
        projectDescriptionTextArea.setRows(5);
        jScrollPane1.setViewportView(projectDescriptionTextArea);

        projectOutcome.setText("Outcome");

        projectTag.setText("Tag");

        projectTagTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                projectTagTextFieldActionPerformed(evt);
            }
        });

        startDate.setText("Start Date");

        addButton.setBackground(new java.awt.Color(255, 255, 255));
        addButton.setText("Add ");
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });

        deleteButton.setBackground(new java.awt.Color(255, 255, 255));
        deleteButton.setText("Delete");
        deleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteButtonActionPerformed(evt);
            }
        });

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 105, Short.MAX_VALUE)
        );

        statusCombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Completed", "In Progress", "Aborted"}));
        statusCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                statusComboActionPerformed(evt);
            }
        });

        endDate.setText("End Date");

        projectOutcomeTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                projectOutcomeTextFieldActionPerformed(evt);
            }
        });

        updateButton.setBackground(new java.awt.Color(255, 255, 255));
        updateButton.setText("Update");
        updateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateButtonActionPerformed(evt);
            }
        });

        org.jdesktop.beansbinding.ELProperty eLProperty = org.jdesktop.beansbinding.ELProperty.create("${resultList}");
        org.jdesktop.swingbinding.JComboBoxBinding jComboBoxBinding = org.jdesktop.swingbinding.SwingBindings.createJComboBoxBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, usersQuery, eLProperty, inchargeCombo);
        bindingGroup.addBinding(jComboBoxBinding);

        AutoCompleteDecorator.decorate(inchargeCombo);

        eLProperty = org.jdesktop.beansbinding.ELProperty.create("${resultList}");
        jComboBoxBinding = org.jdesktop.swingbinding.SwingBindings.createJComboBoxBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, usersQuery1, eLProperty, clientCombo);
        bindingGroup.addBinding(jComboBoxBinding);

        AutoCompleteDecorator.decorate(clientCombo);

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("PROJECT DETAILS");

        javax.swing.GroupLayout projectPaneLayout = new javax.swing.GroupLayout(projectPane);
        projectPane.setLayout(projectPaneLayout);
        projectPaneLayout.setHorizontalGroup(
            projectPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(projectPaneLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(projectPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(projectPaneLayout.createSequentialGroup()
                        .addGroup(projectPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(projectPaneLayout.createSequentialGroup()
                                .addGroup(projectPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(projectOutcome)
                                    .addComponent(inchargeID)
                                    .addComponent(projectName)
                                    .addComponent(clientID)
                                    .addComponent(projectStatus)
                                    .addComponent(projectDescription)
                                    .addComponent(projectTag)
                                    .addComponent(startDate)
                                    .addComponent(endDate))
                                .addGap(38, 38, 38)
                                .addGroup(projectPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(projectNameTextField)
                                    .addComponent(statusCombo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jScrollPane1)
                                    .addComponent(projectOutcomeTextField)
                                    .addComponent(projectTagTextField)
                                    .addComponent(projectStartDate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(projectEndDate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(inchargeCombo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(clientCombo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(projectPaneLayout.createSequentialGroup()
                                .addComponent(addButton, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(87, 87, 87)
                                .addComponent(updateButton, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(69, 69, 69)
                                .addComponent(deleteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 253, Short.MAX_VALUE)))
                .addContainerGap())
        );
        projectPaneLayout.setVerticalGroup(
            projectPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(projectPaneLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addGap(30, 30, 30)
                .addGroup(projectPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(projectName)
                    .addComponent(projectNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(projectPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(inchargeID)
                    .addComponent(inchargeCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(projectPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(clientID)
                    .addComponent(clientCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(projectPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(projectStatus)
                    .addComponent(statusCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(projectPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(projectDescription)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(projectPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(projectOutcomeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(projectOutcome))
                .addGap(18, 18, 18)
                .addGroup(projectPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(projectTag)
                    .addComponent(projectTagTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(projectPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(startDate)
                    .addComponent(projectStartDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(projectPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(endDate)
                    .addComponent(projectEndDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addGroup(projectPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addButton)
                    .addComponent(deleteButton)
                    .addComponent(updateButton))
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(projectPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(projectPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        bindingGroup.bind();
    }// </editor-fold>//GEN-END:initComponents

    private void projectNameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_projectNameTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_projectNameTextFieldActionPerformed

    private void projectTagTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_projectTagTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_projectTagTextFieldActionPerformed

    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
        // TODO add your handling code here:
        String[] array =new String[jtable1.getColumnCount()];
        array[0] = projectNameTextField.getText();
        array[1] = inchargeCombo.getSelectedItem().toString();
        array[2] = clientCombo.getSelectedItem().toString();
        array[3] = (String) statusCombo.getSelectedItem();
        array[4] = projectDescriptionTextArea.getText();
        array[5] = projectOutcomeTextField.getText();
        array[6] = projectTagTextField.getText();
        Date d=projectStartDate.getDate();
        SimpleDateFormat dateFormat = new SimpleDateFormat();
        String stringDate = dateFormat.format(d);
        array[7] = stringDate;
        Date date=projectEndDate.getDate();
        SimpleDateFormat dFormat = new SimpleDateFormat();
        String strDate = dFormat.format(date);
        array[8] = strDate;
        projectController.addRow( array);
    }//GEN-LAST:event_addButtonActionPerformed

    private void deleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButtonActionPerformed
        // TODO add your handling code here:
        String[] array = new String[jtable1.getColumnCount()];
        array[0] = projectNameTextField.getText();
        projectController.deleteRow(array[0]);
        ( (ProjectModel) jtable1.getModel()).fireTableDataChanged();
    }//GEN-LAST:event_deleteButtonActionPerformed

    private void updateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateButtonActionPerformed
        // TODO add your handling code here:
        String[] array =new String[jtable1.getColumnCount()];
        array[0] = projectNameTextField.getText();
        array[1] = inchargeCombo.getSelectedItem().toString();
        array[2] = clientCombo.getSelectedItem().toString();
        array[3] = (String) statusCombo.getSelectedItem();
        array[4] = projectDescriptionTextArea.getText();
        array[5] = projectOutcomeTextField.getText();
        array[6] = projectTagTextField.getText();
        Date d=projectStartDate.getDate();
        SimpleDateFormat dateFormat = new SimpleDateFormat();
        String stringDate = dateFormat.format(d);
        array[7] = stringDate;
        Date date=projectEndDate.getDate();
        SimpleDateFormat dFormat = new SimpleDateFormat();
        String strDate = dFormat.format(date);
        array[8] = strDate;
        projectController.updateRow( array);
        ( (ProjectModel) jtable1.getModel()).fireTableDataChanged();

    }//GEN-LAST:event_updateButtonActionPerformed

    private void statusComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_statusComboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_statusComboActionPerformed

    private void projectOutcomeTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_projectOutcomeTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_projectOutcomeTextFieldActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.persistence.EntityManager PersistenceUnitEntityManager;
    private javax.swing.JButton addButton;
    private org.jdesktop.swingx.JXComboBox clientCombo;
    private javax.swing.JLabel clientID;
    private javax.swing.JButton deleteButton;
    private javax.swing.JLabel endDate;
    private org.jdesktop.swingx.JXComboBox inchargeCombo;
    private javax.swing.JLabel inchargeID;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel projectDescription;
    private javax.swing.JTextArea projectDescriptionTextArea;
    private com.toedter.calendar.JDateChooser projectEndDate;
    private javax.swing.JLabel projectName;
    private javax.swing.JTextField projectNameTextField;
    private javax.swing.JLabel projectOutcome;
    private javax.swing.JTextField projectOutcomeTextField;
    private javax.swing.JPanel projectPane;
    private com.toedter.calendar.JDateChooser projectStartDate;
    private javax.swing.JLabel projectStatus;
    private javax.swing.JLabel projectTag;
    private javax.swing.JTextField projectTagTextField;
    private javax.swing.JLabel startDate;
    private javax.swing.JComboBox statusCombo;
    private javax.swing.JButton updateButton;
    private java.util.List<entity.Users> usersList;
    private java.util.List<entity.Users> usersList1;
    private javax.persistence.Query usersQuery;
    private javax.persistence.Query usersQuery1;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables
}
